name: ci/cd - FE

on:
  workflow_dispatch:

  push:
    branches: [main]

env:
  REACT_APP_BACK_URL : https://backend-final-production.up.railway.app


jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 19
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install packages
        run: npm ci --include=dev

      - name: Run tests
        run: npm run test

  build-push-docker:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hernannavarro/frontend-final:${{ github.run_number }}

  deploy-to-railway:
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node 19
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up -s frontend-final
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}